# -*- coding: utf-8 -*-
"""loanfeats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5VqLg6bqSwZMRFKSx5SvfyxoUf0oZXu
"""

import csv
import pandas as pd
import numpy as np
import pickle
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder



!mv 'gooddf (1).csv' 'gooddf.csv'

with open('goodfeatures.pickle', 'rb') as f:
  y = pickle.load(f)

y = y['loan_status'].to_numpy()
len(y)

with open('gooddf.pickle', 'rb') as f:
  df = pickle.load(f)
  
df = df.drop(['emp_title'], axis = 1)
df['y'] = y

feat = pd.read_csv('features.csv')
category = dict(zip(feat['BrowseNotesFile'].to_list(), feat['status'].to_list()))

cols = df.columns.to_list()

df = df.dropna()

df

feat = pd.read_csv('features.csv')
category = dict(zip(feat['BrowseNotesFile'].to_list(), feat['status'].to_list()))


def one_hot(num_rows, d):
  size = max(d) + 1
  vec = np.zeros((num_rows, size))
  for i in range(size):
    vec[i, d[i]] = 1
  return vec

def
x = np.empty(num_rows, 0)

cols = df.columns.to_list()
num_rows()

for col in cols:

  if col != 'status' and str(category[str(col)]) == '2':
    c = df[col].to_numpy('float32')
    mean = np.mean(c)
    np.hstack(x, c/mean)

  if col != 'status' and str(category[str(col)]) == '1':
    c = df[col].to_list()
    le = preprocessing.LabelEncoder()
    le.fit(c)
    d = le.transform(c)
    np.hstack(x, one_hot(num_rows, d))

feat = pd.read_csv('features_new.csv')
category = dict(zip(feat['_browse_notes_file'].to_list(), feat['status'].to_list()))

def one_hot(num_rows, d):
  size = max(d) + 1
  vec = np.zeros((num_rows, size))
  for i in range(size):
    vec[i, d[i]] = 1
  return vec

def get_train(df):
  x = np.empty(num_rows, 0)
  cols = df.columns.to_list()
  num_rows = len(df)

  for col in cols:

    if col != 'status' and str(category[str(col)]) == '2':
      c = df[col].to_numpy('float32')
      mean = np.mean(c)
      np.hstack(x, c/mean)

    if col != 'status' and str(category[str(col)]) == '1':
      c = df[col].to_list()
      le = preprocessing.LabelEncoder()
      le.fit(c)
      d = le.transform(c)
      np.hstack(x, one_hot(num_rows, d))
  
  y = df['status'].to_numpy()
  df.drop('status', axis = 1)

  return x, y

x = np.zeros((5, 5))
d = [1, 2, 3, 4, 0]
num_rows = 5

def one_hot(d):
  size = max(d) + 1
  vec = np.zeros((num_rows, size))
  for i in range(size):
    vec[i, d[i]] = 1
  return vec

one_hot(d)

y = df['y'].to_numpy()
with open('loans_y.npy', 'wb') as f:
  np.save(f, y)

df.drop('y', axis=1)
x = df.to_numpy()

from collections import Counter
cnt = Counter(z)

z = y == 'Fully Paid'

cnt.most_common()