# -*- coding: utf-8 -*-
"""loanclean.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sf_FyQ8j8Zsh_Vo0Qiwc9Mo6FyGZtT3B
"""

import csv
import pandas as pd
import numpy as np
import sklearn
import pickle

df = pd.read_csv("new_loan.csv")
df

df2 = pd.read_csv("loan_status.csv")
df2['indices'] = range(0,2139958)
df2

df3 = df2[df2.loan_status == 'Current']
drops = df3['indices'].to_list()
drops

df4 = df.drop(drops)
df5 = df2.drop(drops)
df4

featuredf = pd.read_csv("features.csv")
featuredf

bnflist = featuredf['BrowseNotesFile'].to_list()
status = featuredf['status'].to_list()
d = dict(zip(bnflist,status))
d

df4 = df4.drop('Unnamed: 0',axis = 1)

df4['term'] = df4['term'].str.replace(r'\D', '')
df4

for i in range(0,66):
  s = df4.columns[i]
  t = d[s]
  if(t == 2):

nan_values = df4.isna()
nan_columns = nan_values.any()

columns_with_nan = df4.columns[nan_columns].tolist()

df4.isna().sum().to_list()

len(df4.isna().sum(axis = 1).to_numpy() > 0)

set(df2['loan_status'].to_list())

df4 = df4.drop('desc', axis = 1)

len(df4.isna().sum(axis = 1).to_numpy() > 0)

x = df4.isna().sum().to_frame()
pd.set_option('display.max_rows', x.shape[0]+1)
x

removelist = ['mths_since_last_major_derog', 'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il',
'il_util'	,
'open_rv_12m',
'open_rv_24m'	,
'max_bal_bc',
'all_util',
'inq_fi',
'total_cu_tl',
'inq_last_12m']
df4 = df4.drop(removelist, axis = 1)

df4

nans = df4.isna().sum(axis = 1).to_numpy()
nans

nans2 = nans > 0
len(nans2)

gooddf = df4.dropna()
gooddf

droplist = []
for i in range(0,1314044):
  if(nans[i]):
    droplist.append(i)
droplist

df5 = df5.reset_index()

goodfeatures = df5.drop(droplist)
goodfeatures

gooddf.to_pickle("gooddf.pickle")

goodfeatures.to_pickle('goodfeatures.pickle')

gooddf

